name: 'WordPress Plugin Deploy'
description: 'Deploy to the WordPress Plugin Repository'
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

inputs:
  generate-zip:
    description: 'Generate package zip file?'
    default: false
outputs:
  zip-path:
    description: 'Path to zip file'
    value: ${{ steps.deploy.outputs.zip-path }}
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run a one-line script
        env:
          INPUT_GENERATE_ZIP: ${{ inputs.generate-zip }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: readmore
        run: ${{ github.action_path }}/deploy.sh
